parameters:

  a: 0.20829553260892103
  b: 0.20829553260892103
  c: 0.9900284346227157
  sig1: 1.5
  sig2: 1.25
  sig3: 1.7
  alpha: 0.85
  beta: 0.25
  xi: 1.0

initial_conditions:

  p: 0.3
  q: 0.3
  r: 0.3
