parameters:

  a: 2.7917044673910785
  b: 2.7917044673910785
  c: 0.20829553260892103
  sig1: 1.5
  sig2: 1.25
  sig3: 1.7
  alpha: 0.85
  beta: 0.25
  xi: 0.0

initial_conditions:

  p: 0.3
  q: 0.3
  r: 0.3
