parameters:

  a: 2.0099715653772847
  b: 0.20829553260892103
  c: 2.7917044673910785
  sig1: 1.5
  sig2: 1.25
  sig3: 1.7
  alpha: 0.85
  beta: 0.25
  xi: 0.0

initial_conditions:

  p: 0.3
  q: 0.3
  r: 0.3
